name = "High Contrast"

[colors.background]
r = 0
g = 0
b = 0
a = 255

[colors.background_secondary]
r = 20
g = 20
b = 20
a = 255

[colors.background_tertiary]
r = 40
g = 40
b = 40
a = 255

[colors.text_primary]
r = 255
g = 255
b = 255
a = 255

[colors.text_secondary]
r = 220
g = 220
b = 220
a = 255

[colors.text_disabled]
r = 150
g = 150
b = 150
a = 255

[colors.border]
r = 255
g = 255
b = 255
a = 255

[colors.selection]
r = 0
g = 120
b = 215
a = 100

[colors.cursor]
r = 255
g = 255
b = 0
a = 255

[colors.highlight]
r = 255
g = 255
b = 0
a = 50

[colors.block_running]
r = 0
g = 150
b = 255
a = 255

[colors.block_success]
r = 0
g = 255
b = 0
a = 255

[colors.block_error]
r = 255
g = 0
b = 0
a = 255

[colors.block_editing]
r = 255
g = 255
b = 0
a = 255

[colors.ansi_black]
r = 0
g = 0
b = 0
a = 255

[colors.ansi_red]
r = 255
g = 0
b = 0
a = 255

[colors.ansi_green]
r = 0
g = 255
b = 0
a = 255

[colors.ansi_yellow]
r = 255
g = 255
b = 0
a = 255

[colors.ansi_blue]
r = 0
g = 150
b = 255
a = 255

[colors.ansi_magenta]
r = 255
g = 0
b = 255
a = 255

[colors.ansi_cyan]
r = 0
g = 255
b = 255
a = 255

[colors.ansi_white]
r = 255
g = 255
b = 255
a = 255

[colors.ansi_bright_black]
r = 100
g = 100
b = 100
a = 255

[colors.ansi_bright_red]
r = 255
g = 100
b = 100
a = 255

[colors.ansi_bright_green]
r = 100
g = 255
b = 100
a = 255

[colors.ansi_bright_yellow]
r = 255
g = 255
b = 100
a = 255

[colors.ansi_bright_blue]
r = 100
g = 200
b = 255
a = 255

[colors.ansi_bright_magenta]
r = 255
g = 100
b = 255
a = 255

[colors.ansi_bright_cyan]
r = 100
g = 255
b = 255
a = 255

[colors.ansi_bright_white]
r = 255
g = 255
b = 255
a = 255

[fonts]
family = "monospace"
size = 14.0
line_height = 1.5

[spacing]
block_spacing = 12.0
padding = 10.0
border_width = 2.0
border_radius = 2.0

[syntax.keyword]
r = 255
g = 100
b = 255
a = 255

[syntax.string]
r = 0
g = 255
b = 100
a = 255

[syntax.comment]
r = 150
g = 150
b = 150
a = 255

[syntax.function]
r = 100
g = 200
b = 255
a = 255

[syntax.variable]
r = 255
g = 255
b = 255
a = 255

[syntax.number]
r = 255
g = 200
b = 100
a = 255

[syntax.operator]
r = 0
g = 255
b = 255
a = 255

[syntax.type_name]
r = 255
g = 255
b = 0
a = 255
