name = "Warp"

[colors.background]
r = 35
g = 40
b = 50
a = 255

[colors.background_secondary]
r = 42
g = 47
b = 57
a = 255

[colors.background_tertiary]
r = 50
g = 55
b = 65
a = 255

[colors.text_primary]
r = 220
g = 225
b = 235
a = 255

[colors.text_secondary]
r = 180
g = 185
b = 195
a = 255

[colors.text_disabled]
r = 120
g = 125
b = 135
a = 255

[colors.border]
r = 70
g = 75
b = 85
a = 255

[colors.selection]
r = 100
g = 150
b = 255
a = 60

[colors.cursor]
r = 255
g = 200
b = 100
a = 255

[colors.highlight]
r = 100
g = 150
b = 255
a = 30

[colors.block_running]
r = 100
g = 150
b = 255
a = 255

[colors.block_success]
r = 100
g = 200
b = 150
a = 255

[colors.block_error]
r = 255
g = 100
b = 100
a = 255

[colors.block_editing]
r = 255
g = 200
b = 100
a = 255

[colors.ansi_black]
r = 50
g = 55
b = 65
a = 255

[colors.ansi_red]
r = 255
g = 100
b = 100
a = 255

[colors.ansi_green]
r = 100
g = 200
b = 150
a = 255

[colors.ansi_yellow]
r = 255
g = 200
b = 100
a = 255

[colors.ansi_blue]
r = 100
g = 150
b = 255
a = 255

[colors.ansi_magenta]
r = 200
g = 150
b = 255
a = 255

[colors.ansi_cyan]
r = 100
g = 200
b = 200
a = 255

[colors.ansi_white]
r = 220
g = 225
b = 235
a = 255

[colors.ansi_bright_black]
r = 100
g = 105
b = 115
a = 255

[colors.ansi_bright_red]
r = 255
g = 130
b = 130
a = 255

[colors.ansi_bright_green]
r = 130
g = 220
b = 170
a = 255

[colors.ansi_bright_yellow]
r = 255
g = 220
b = 130
a = 255

[colors.ansi_bright_blue]
r = 130
g = 170
b = 255
a = 255

[colors.ansi_bright_magenta]
r = 220
g = 170
b = 255
a = 255

[colors.ansi_bright_cyan]
r = 130
g = 220
b = 220
a = 255

[colors.ansi_bright_white]
r = 240
g = 245
b = 255
a = 255

[fonts]
family = "monospace"
size = 14.0
line_height = 1.600000023841858

[spacing]
block_spacing = 12.0
padding = 10.0
border_width = 1.0
border_radius = 6.0

[syntax.keyword]
r = 200
g = 150
b = 255
a = 255

[syntax.string]
r = 100
g = 200
b = 150
a = 255

[syntax.comment]
r = 120
g = 125
b = 135
a = 255

[syntax.function]
r = 100
g = 150
b = 255
a = 255

[syntax.variable]
r = 220
g = 225
b = 235
a = 255

[syntax.number]
r = 255
g = 200
b = 100
a = 255

[syntax.operator]
r = 100
g = 200
b = 200
a = 255

[syntax.type_name]
r = 255
g = 220
b = 130
a = 255
